cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    dank:
      failed_login_attempts: 0
      logged_in: false
      name: Dank
      password: $2b$12$JNYpunP65fNJ.X1o4a3E6umKMCPHbjtFyOZQu7Wl.mkzYjF4utCOC
      status: Active
    hint:
      failed_login_attempts: 0
      logged_in: true
      name: Hint
      password: $2b$12$eRbrZ4vv43qVmpBM/Xldw.oHFctDRQSbByxyYjxICP96AD1QH5Zii
      status: Active
    lam:
      failed_login_attempts: 0
      logged_in: true
      name: Lam
      password: $2b$12$6wjMkgHClYEb2RJx2qd/3uiehVpLAWIOYSa5eWaX00tD4SgWyA5Pa
      status: Busy
    moi:
      failed_login_attempts: 0
      logged_in: false
      name: Moi
      password: $2b$12$/wbHt1NmYuASfwuoHEIv0O/XONXgQ2FXzzsuy5NJtKWH3qgkdXdce
      status: Active
pre-authorized:
  name:
  - Dank
